### ISSUE TITLE
how to fix this

### ISSUE THREAD

**Issue by xXAloneX** [hlnajz/rosettaWizard#3]
![image](https://github.com/user-attachments/assets/b8a311c5-ce55-43e6-862a-0469d9986521)
![image](https://github.com/user-attachments/assets/d400ba2e-b457-4a61-b8b2-810fa520fe99)

**Comment by najzdev** [comment]
Hello brother I will make video tomorrow unchallah how to work with it in my channel hlnajz on YouTube

**Comment by xXAloneX** [comment]
![image](https://github.com/user-attachments/assets/26aee430-247b-4697-8f1e-210824fd177c)
still same probleme for b2

**Comment by najzdev** [comment]
Just be patient, right now the server of Rosetta Stone is shut down, try later, also follow me on GitHub for more stuff like that,
Thanks
