### ISSUE TITLE
Too more no needed complexity 

### ISSUE THREAD

**Issue by ysfzxz7** [hlnajz/rosettaWizard#5]
I have a better Solution to this, You can Contact me for more information 👋

**Comment by champinnit** [comment]
where can i contact you😊?]

**Comment by 0xyaci** [comment]
> I have a better Solution to this, You can Contact me for more information 👋

I need that solution. (i followed you on x)

**Comment by najzdev** [comment]
> where can i contact you😊?]
> 

Why?

**Comment by najzdev** [comment]
> I have a better Solution to this, You can Contact me for more information 👋

No need Thanks

**Comment by champinnit** [comment]
For me l extension doesnt work it didnt add any hours, went over all the steps correctly. Also there is always wahd "2 issues" mark on the extension

**Comment by champinnit** [comment]
> > where can i contact you😊?]
> > 
> 
> Why? 
For me l extension doesnt work it didnt add any hours, went over all the steps correctly. Also there is always wahd "2 issues" mark on the extension

**Comment by champinnit** [comment]
> > I have a better Solution to this, You can Contact me for more information 👋
> For me l extension doesnt work it didnt add any hours, went over all the steps correctly. Also there is always wahd "2 issues" mark on the extension
> No need Thanks

**Comment by champinnit** [comment]
> > I have a better Solution to this, You can Contact me for more information 👋
> 
> No need Thanks 
For me l extension doesnt work it didnt add any hours, went over all the steps correctly. Also there is always wahd "2 issues" mark on the extension
